import Link from "next/link";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio-site",
  description: "Generated by next-sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all of our pages
  const pages = await getPages();
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-red-400 via-green-400 to-yellow-400 bg-clip-text text-transparent text-lg font-bold"
          >
            Home
          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-500 ">
            {pages.map((page) => (
              <Link
                className="hover:underline"
                href={`/${page.slug}`}
                key={page._id}
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
